# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_opencart
      - MARIADB_ROOT_PASSWORD=ENTER
      - MARIADB_DATABASE=bitnami_opencart
      - MARIADB_PASSWORD=ENTER
    volumes:
      - './site/mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:latest
    ports:
      - '80:8080'
      - '443:8443'
      - '3306:3306'
    environment:
      - OPENCART_HOST=192.168.0.1
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=80
      - OPENCART_EXTERNAL_HTTPS_PORT_NUMBER=443
      - OPENCART_ENABLE_HTTPS=yes
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      #- OPENCART_DATABASE_PASSWORD=ENTER
      - OPENCART_DATABASE_PASSWORD=ENTER
      #- OPENCART_USER=admintravel
      #- OPENCART_PASSWORD=ENTER
      #- OPENCART_EMAIL=adminemail@gmail.com
      #- OPENCART_SMTP_HOST=smtp.gmail.com
      #- OPENCART_SMTP_PORT=587
      #- OPENCART_SMTP_USER=adminemail@gmail.com
      #- OPENCART_SMTP_PASSWORD=ENTER
    volumes:
      - './site/opencart_data:/bitnami/opencart'
      - './site/opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
